# 端口配置
server:
  port: 8883
  http:
    port: 8333
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/baichengfu_prod?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 200
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 3000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,wall,slf4j
    remove-abandoned: true
    remove-abandoned-time-out: 1800
    stat-view-servlet:
      url-pattern: /druid/*
      allow: 127.0.0.1
      login-username: root
      login-password: root
  ############################################### REDIS ###################################################################
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10
        max-wait: -1ms


############################################## MYBATIS #################################################################
mybatis:
  mapper-locations[0]: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.yihukurama.sysbase.model

#短信配置
sms:
  accesskey: vkhg0Tc54SpjigJa
  secret: PiARb4xmDKc4ek1vit8EpQnd5tPNnqC1
#微信登录配置
wxapp:
  appId:
  appSecret:
#系统配置
system:
  saveFilePath: /root/prod/baichengfu/file
  accesslog: logs/
  redisPrefix: baichengfu-redis-sitpre


alipay:
  appId: 2021001159612742
  aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiGmRqGSrRjJZ2J/IjJ82J+KDWgm3wJrETeT/DNoqJzut1tcBurDxAXxAVKt40CQl2I6fSQPhFZ7kw2Pk4J6EWI8kd/CogHEA9O15XNrV6nfrLtcZnbnSgdv5rcUxXbe82GtNNX1II4F9yBHglDOuDppdHv4kTGpTxS/QeaqPXV54nlzbhRybTTWmy/YilmM+6MR1vjb7V90rgpodK3NfZR4DG6x35B0KpVVKdkh3di/gKPJ+4ezupJrEtmDPs79MQfK5eaAc75bkTQLh9LCziGHO15WO8/BGd+ncZdBZlKAhADJi3ERjl3W/fFaee2ONyjPXD+FiYxoctZXh7vjL7QIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcMFBbRlfQEfvBwqG0CjzY9kqERTffYkYTBIT3rSMiZnHaNJ3X3e+buF5rhIdE9Mw7g0WYR6zrC64i8H3O4ZY4rQ/Gsl75xVjZVyzpqB7ohsYzbPqECBRpiNjsa5pQMF/7S/dQWKrYgXfCThfPnlwPF4Fz1hGw1GY2ObqyXvpohUWoAboE2mSg8aqRN46+tu1Szpmmdy8diRejx2v3bKjlA2XDlCFfnZJZvxfEdWL0tIgXZUimQgRx+kTxbrYtRqr2TYhXgFRTPFIbfB+gJRImXyAOzXu3DUGWmX+MGPKOxpcFELhs33XHTLRFigW6LFoa9MrZ11R5PSwJ/3xye99nAgMBAAECggEALHuSFzzEe6zzf66X8TfNNpmGhX9VN1i8zmPGHuf/jqeQm23K2pUJzdbHhWWcROZXWEe9xW38cIDGGotVuVsENqYLTTK12/r5oAS09OL90om33yOVgY7viVMBPOw0acwtOdvb1tU56ymMWxl0rJvUajPumXgJV8xWQ/FTG8PzG1sM/iL1nebscOl1M1ZPJ5kjHUEDliKXdf9Iu7GmeHJqWvjAs7XWmjk1vZnIcQp0i9nzMAFeD3uRsl3jD/eONRDT/zIWn1/qdCpnSG8lt8r4PFT648fRM0nI2ozVX3EVrWwv0yNasaCn2w9h4VX2KD+ihuQarKAIE9JlBLbUKeHomQKBgQD36G44i7+Uy7PC3uUtYQT1MQLGk9SFGQ2F/WKTgtXWka9LIgDA1AdQuMT12Z0Kl+SVwKzQaDW/Y7AkgIT21jWJqd2BV8r9HLbcR7BtQKNvs7nigN/RoGYtXBoIhqFA4W2I6aHvXERLFUF9GOoZPwmWYJojvoQlVprsw3QmXStgYwKBgQChSXV44BZLdAAPbucv1y7k4kAe2VReKaQ5tNhF4+DcUZzUAO6mSaw6pnTDJUZLWyVaQwR660CiE0YkseOBJTzsPyVnW5FFb8IToGJRg9RPry7KTmbzcAXreaJ7T39jBoOm70Qv9XjYDLo9brVMqjzaw0Y1ejoBq54pge894Ry6LQKBgQCnpW/8H01Ec2iyDIfQ4z42DZnB7jCWfXWuucaS2LSBMO3pEiqOPBRiW0EevLW9dzBmsPBs0zwdnG1+kcbZIcz8tnmLwXINLwDeAEDn8QFVRaYb7WjuWtkeLZ2RTHH57ThkkRIoSy4H1G0ACvwsbHuwTM2QBINauLF2EUsXsoPl3wKBgFyE4QgXs3JQ9n/j5GZDD7loN9P6YzUoufYIUU+2KpT3k/jhGAT3mf6C4dPXm/06KbEfZICGVqsiV0hRaun4THxQtMoXcrvcIf5UMFIGR1H2cebHFrNqfVrYiWYm8jIB2J93/SttqoZ0tpjq2sFBnmr3PV0L4h53LeEtkelzKqF5AoGAcIUemhXC3m/pfhIjbOkgNFvAUtqrZpz1YKngl5cTkcinUI4lttPT6S+ib+C8LL5NF4Jo9ClzsmFaNisMnGTcVmVBbuL1XO7ek0ltqgO6hCdFlPns7+m/4qBgYJbj8HB0If6fBiCW2tcEkFYKPIqgLFlKH0LvnbaJtogkHbI+aYo=
  returnUrl: http://xxxxx
  notifyUrl: http://xxxxx

wxpayconfig:
  appId: xxxxx
  miniAppId: xxxxx
  appAppId: xxxxx
  mchId: xxxxxx
  mchKey: xxxxxxx
  notifyUrl: http://xxxxx


# 用户名（这里为空）
mqtt:
  username: admin
  # 密码（这里为空）
  password: baichengfu
  # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:1883,tcp://192.168.60.133:1883
  url: tcp://8.129.180.116:1883
  # 生产者连接服务器默认客户端ID
  sender:
    clientId: mqttProducer
    # 默认的推送主题，实际可在调用接口时指定
    defaultTopic: hangge
  # 消费者连接服务器默认客户端ID（这里使用随机数）
  receiver:
    clientId: ${random.value}
    # 默认的接收主题，实际可在调用接口时指定
    defaultTopic: hangge